name: Terraform Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # exported as a JSON blob

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Init Terraform
      run: terraform init

    - name: Fetch Secrets from Key Vault
      run: |
        SSH_KEY=$(az keyvault secret show \
          --name ssh-public-key \
          --vault-name kv-webserver-dev2 \
          --query value -o tsv)

        ALLOWED_IP=$(az keyvault secret show \
          --name allowed-ssh-ip \
          --vault-name kv-webserver-dev2 \
          --query value -o tsv)

        echo "SSH_KEY=$SSH_KEY" >> $GITHUB_ENV
        echo "ALLOWED_IP=$ALLOWED_IP" >> $GITHUB_ENV

    - name: Terraform Plan
      run: terraform plan -var "ssh_key=$SSH_KEY" -var "allowed_ssh_ip=$ALLOWED_IP"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var "ssh_key=$SSH_KEY" -var "allowed_ssh_ip=$ALLOWED_IP"
